#!/usr/bin/env python3
"""Inspect a project and write a lightweight project scan memory file."""

from __future__ import annotations

import json
import argparse
import shutil
from pathlib import Path


GENERATED = "<!-- ai-engineering:generated -->"


SIGNALS = {
    "Node.js": ["package.json", "pnpm-lock.yaml", "yarn.lock", "package-lock.json"],
    "Python": ["pyproject.toml", "requirements.txt", "setup.py", "Pipfile"],
    "Go": ["go.mod"],
    "Rust": ["Cargo.toml"],
    "Java/Maven": ["pom.xml"],
    "Java/Gradle": ["build.gradle", "build.gradle.kts", "settings.gradle"],
    "Docker": ["Dockerfile", "docker-compose.yml", "compose.yml"],
}


COMMON_DIRS = [
    "src",
    "app",
    "lib",
    "cmd",
    "internal",
    "pkg",
    "tests",
    "test",
    "__tests__",
    "docs",
    "config",
    "migrations",
]


# 扫描一层子目录时跳过的目录(依赖、构建产物、版本控制、框架自身产物)
SKIP_DIRS = {
    "node_modules", "vendor", "dist", "build", "target",
    ".git", ".venv", "venv", "__pycache__", ".tox", "docs", ".github",
}


def exists_any(root: Path, names: list[str]) -> list[str]:
    return [name for name in names if (root / name).exists()]


def node_runner(root: Path) -> str:
    if (root / "pnpm-lock.yaml").exists():
        return "pnpm"
    if (root / "yarn.lock").exists():
        return "yarn"
    return "npm run"


def detect_commands(root: Path) -> list[str]:
    commands: list[str] = []

    package_json = root / "package.json"
    if package_json.exists():
        runner = node_runner(root)
        try:
            data = json.loads(package_json.read_text(encoding="utf-8"))
            scripts = data.get("scripts", {})
            for name in ["test", "lint", "typecheck", "build", "dev"]:
                if name in scripts:
                    commands.append(f"{runner} {name}")
        except Exception:
            commands.append("npm test")

    if (root / "go.mod").exists():
        commands.append("go test ./...")

    if (root / "pyproject.toml").exists() or (root / "requirements.txt").exists():
        if (root / "pytest.ini").exists() or shutil.which("pytest"):
            commands.append("pytest")
        else:
            commands.append("python -m unittest discover")

    if (root / "Cargo.toml").exists():
        commands.append("cargo test")

    if (root / "pom.xml").exists():
        commands.append("mvn test")

    if (root / "build.gradle").exists() or (root / "build.gradle.kts").exists():
        if (root / "gradlew.bat").exists():
            commands.append("./gradlew.bat test")
        elif (root / "gradlew").exists():
            commands.append("./gradlew test")
        else:
            commands.append("gradle test")

    return commands


def detect_subprojects(root: Path) -> list[tuple[str, dict[str, list[str]], list[str]]]:
    """扫描一层子目录,返回含技术栈标记的子项目 (name, detected, commands)。支持 monorepo。"""
    subs: list[tuple[str, dict[str, list[str]], list[str]]] = []
    for child in sorted(p for p in root.iterdir() if p.is_dir()):
        if child.name.startswith(".") or child.name in SKIP_DIRS:
            continue
        detected = {stack: matched for stack, names in SIGNALS.items() if (matched := exists_any(child, names))}
        if detected:
            subs.append((child.name, detected, detect_commands(child)))
    return subs


def is_generated_scan(content: str) -> bool:
    # 只认显式 GENERATED 标记;不再用宽泛的 legacy 文本子串,避免误判并覆盖用户手写文件
    return GENERATED in content


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("target", help="Target project path.")
    parser.add_argument("--force", action="store_true", help="Overwrite project scan.")
    args = parser.parse_args()

    root = Path(args.target).expanduser().resolve()
    if not root.exists() or not root.is_dir():
        raise SystemExit(f"Target project does not exist: {root}")

    detected = {
        stack: exists_any(root, files)
        for stack, files in SIGNALS.items()
        if exists_any(root, files)
    }
    dirs = [name for name in COMMON_DIRS if (root / name).is_dir()]
    commands = detect_commands(root)

    output = root / "docs" / "memory" / "project-scan.md"
    if output.exists() and not args.force:
        existing = output.read_text(encoding="utf-8", errors="ignore")
        if not is_generated_scan(existing):
            print(f"skip existing: {output}")
            return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Project Scan",
        "",
        "This file is generated by the ai-engineering-discipline skill. Review it before treating it as a rule source.",
        "",
        "## Detected Stack Signals",
        "",
    ]

    if detected:
        for stack, files in detected.items():
            lines.append(f"- {stack}: `{', '.join(files)}`")
    else:
        lines.append("- No common stack marker detected.")

    lines.extend(["", "## Important Directories", ""])
    if dirs:
        for name in dirs:
            lines.append(f"- `{name}/`")
    else:
        lines.append("- No common source/test directory detected.")

    lines.extend(["", "## Candidate Commands", ""])
    if commands:
        for command in commands:
            lines.append(f"- `{command}`")
    else:
        lines.append("- No common build/test command detected. Inspect the project manually.")

    subprojects = detect_subprojects(root)
    if subprojects:
        lines.extend(["", "## Subprojects (one level)", ""])
        for name, sub_detected, sub_commands in subprojects:
            stacks = ", ".join(sub_detected.keys())
            cmds = "; ".join(f"`cd {name} && {c}`" for c in sub_commands) or "—"
            lines.append(f"- `{name}/` — {stacks} — {cmds}")

    lines.extend([
        "",
        "## Follow-Up",
        "",
        "- Confirm actual build, test, lint, and typecheck commands.",
        "- Move confirmed rules into `project-rules.md`.",
        "- Move confirmed module boundaries into `module-map.md`.",
    ])

    output.write_text(GENERATED + "\n" + "\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
